name: CI for CubeIt

on:
  - push

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install pytest-playwright

      - name: Install browsers
        run: python -m playwright install --with-deps

      - name: Run tests
        run: |
          python -m http.server 8000 &
          pytest
